# Generated by Django 3.1.5 on 2021-01-31 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0003_businesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('1', 'Urgent'), ('2', 'Necessary'), ('3', 'Unessential')], default='None', max_length=50)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('poster_id', models.IntegerField(default=0)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='hood.profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
